blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:no>/', views.detail, name='detail'),
    path("test1/", views.test1),
    path('test2/<no>/', views.test2),
    path('blog/profile/', views.profile),
    path('tag/<id>/', views.tag_list),
    path('test3/', views.test3),
    path('new/', views.post_create, name='create'),
    path('update/<id>/', views.post_update, name='update'),
    path('delete/<id>/', views.post_delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls')),
    path('book/', include('book.urls')),
    path('gallery/', include('gallery.urls')),
    path('accounts/', include('accounts.urls')),
]

from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

# models.py 수정하면 반드시 migrate 해줘야함.! 만들고 db에 적용하기
#python manage.py makemigrations blog
#python manage.py migrate blog


class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    ip = models.GenericIPAddressField(null=True)
    tag = models.ManyToManyField('Tag', null=True, blank=True)
    
    # str 매서드 지정: 인스턴스만의 고유한 값으로 출력되도록 지정(선택 사항)  -> title 이름으로 보여짐.
    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.id])
    
    
    
    """# title과 autoincremente된 id가 같이 나오게 수정
    def __str__(self) :
        return str(self.id) + ":" + self.title"""
        
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=20)
    message = models.TextField()
    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True) #값이 중복을 허용하지 않도록 unique지정
    
    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=50)

blog/forms.py
from django import forms
from blog.models import Post

class PostForm(forms.Form):
    title = forms.CharField(label='제목')
    body = forms.CharField(label='내용', widget=forms.Textarea)


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']
        

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.

# 뷰객체: 서비스 처리 객체
def test1(request):
    #서비스 구현
    return HttpResponse('Good Luck')



def test2(request, no):
    #서비스 구현
    print(type(no))
    return HttpResponse(f"no : {no}")



#전체 목록 보기
def list(request):
    post_list = Post.objects.all()   # model객체 사용해서 view에서 서비스 실행 함수 작성 -> return 값은 QuerySet이 리스트형태로 나옴. 
    search_key = request.GET.get('keyword')
    if search_key:
        post_list = Post.objects.filter(title__contains=search_key)
    
    return render(request, 'blog/list.html', {'post_all': post_list, 'q': search_key})



#상세 보기 (아래 코드를 get_object_or_404로 간단하게 구현 가능 -> 없는 id값 넣으면 404 페이지 출력됨)
def detail(request, no):
    post = get_object_or_404(Post, id=no) #get 매서드 사용해서 결과값 1개: post 인스턴스임
    comment_list = post.comments.all()    #QuerySet임. 리스트 형태.
    tag_list = post.tag.all()
    return render(request, 'blog/detail.html', {'post': post, 
                                                'comment_all': comment_list,
                                                'tag_list': tag_list,})


def profile(request):
    user = User.objects.first()
    return render(request, 'blog/profile.html', {'user': user})



def tag_list(request, id):
    tag = Tag.objects.get(id=id)
    post_list = tag.post_set.all()
    return render(request, 'blog/list.html', {'post_all': post_list})
    


def test3(request):
    print('요청 방식: ', request.method)
    print('Get방식으로 정달된 문자열: ', request.GET)
    print('Post방식으로 전달된 문자열: ', request.POST)
    return render(request, 'blog/form_test.html')


# Form 기반 Data 생성 작업
def post_create(request):
    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid(): # 유효성 검사함 -> cleaned_data = {} 딕셔너리 객체가 생성됨
            print('cleaned_data: ', form.cleaned_data)
            #DB에 추가
            #post = Post.objects.create(**form.cleaned_data)
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            post = form.save()
            return redirect(post)
    else:
        form = PostModelForm()
        
    return render(request, 'blog/post_form.html', {'form': form}) # 비어있는 폼



# Form 기반 Data 수정 작업
#'update/<id>/' <- 여기 url에 id에 값이 들어감.
def post_update(request, id):
    post = get_object_or_404(Post, id=id) #db에서 선택한 id와 같은 데이터를 db에서 뽑아냄.
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post) #save()가 추가, 수정이 다 가능하므로 위에 생성코드와 구별하기 위해 instance=post해줘서 db에서 가져온 데이터로 update임을 명시함.
        if form.is_valid():
            form.save()
            return redirect('blog:list')
    else:
        form = PostModelForm(instance=post) # form의 기본값 지정 : 바로 위에서 db에서 뽑아온 데이터를 form의 기본값으로 넣어주는 거임.instance 메서드 활용. 그냥 = 해서 넣어주면 됨.
        
    return render(request, 'blog/post_update.html', {'form': form}) # 수정작업이니까 기존에 채워져있던 값이 보여지는 폼으로 만들어야함
                                                                    # 그 값은 id에서 선택한 것에 해당하는 데이터를 db에서 가져옴.
    
    
# Data 삭제 작업
def post_delete(request, id):
    post = get_object_or_404(Post, id=id) #앞의 id는 필드명, 뒤의 id는 path 변수.
    if request.method == 'POST':
        post.delete()
        return redirect('blog:list')
        
    else:
        return render(request, 'blog/post_delete.html', {'post':post}) #delete 템플릿에 가보면 {{post}}로 context 보여주기때문에 'post'를 key에 적어준 거임.







"""#상세 보기
def detail(request, no): 
    try:
        post = Post.objects.get(id=no)
    
    except:
        return HttpResponse('존재하지 않는 데이터입니다.')
        
    return HttpResponse(post.title)"""

blog/templates/blog/detail.html
{% extends "layout.html" %}

{% block title %}상세 보기{% endblock title %}

{% block content %}

  <h1>  {{post.title}} </h1>

  제목 : {{post.title}} <br>
  내용 : {{post.body}}  <br>

  <hr>
  <p>댓글</p>
  {% for comment in comment_all %}
    <p>{{comment.message}}/{{comment.author}}/{{comment.updated}}</p>
  {% empty %}
    <p> 댓글이 존재하지 않습니다. </p>
  {% endfor %}
  
  <hr>
  <p>태그</p>
  {% for tag in tag_list %}
     #   <a href='/blog/tag/{{tag.id}}/'> {{tag.name}} </a>
  {%endfor%}
   

  <p><a href="{% url 'blog:list'  %}"> [목록 보기] </a></p>
  <p><a href="{% url 'blog:update' post.id  %}"> [글 수정] </a></p>  
  <p><a href="{% url 'blog:delete' post.id  %}"> [삭제] </a></p>  

{% endblock content %}

blog/templates/blog/form_test.html
{% extends "layout.html" %}
{% block title %} Form Test {% endblock %}
{% block content %}
    <form action="" method="get">    
        {% csrf_token %}
        아이디 : <input type="text" name="id" value="user1"><br>
        비밀번호 : <input type="password" name="pwd" value="12345"><br>
        성별 :     
        <input type="radio" name="gender" value="male" checked > 남자
        <input type="radio" name="gender" value="female"> 여자 <br>
        
        관심분야:
        <input type="checkbox" name="interest" value="AI" checked >인공지능 
        <input type="checkbox" name="interest" value="BD">빅데이터 
        <input type="checkbox" name="interest" value="DA" checked >데이터 분석 <br>

        연령대:
        <select name="age">
            <option value="2">20대</option>
            <option value="3">30대</option>
            <option value="4" selected >40대</option>         
        </select><br>

        참고 사항: <br>
        <textarea cols="30" rows="10" name="remark">통계학 전공</textarea><br>
        <input type="submit" value="확인">
    </form>
{% endblock %}

blog/templates/blog/list.html
{% extends "layout.html" %}

{% block title %}Post 목록 보기{% endblock title %}

{% block content %}

  <h1>Post 목록 보기</h1>
  
  <form action='' method='get'>
    {% csrf_token %}
    검색어: <input type='text' name='keyword' value="{{q|default:''}}">
    <input type='submit' value='검색'>
  </form>

  {% for post in post_all %}
  
  <a href= "/blog/{{post.id}}"> {{post.title}} </a><br>

  {% endfor %}
  
  <a href="{% url 'blog:create' %}">[새 글 쓰기]</a>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "layout.html" %}
{% block title %}Post 삭제{% endblock %}
{% block content %}
    <h1> POST 삭제</h1>
    {{post}}  글을 정말로 삭제하시겠습니까?

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="네, 삭제합니다">
    </form>

    <a href="{% url 'blog:list'%}">아니오, 취소합니다</a>
    
{% endblock %}

blog/templates/blog/post_form.html
{% extends "layout.html" %}
{% block title %} Post 등록 {% endblock %}
{% block content %}
    <h1> POST 등록</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="등록">
    </form>
{% endblock %}

blog/templates/blog/post_update.html
{% extends "layout.html" %}

{% block title %}Post 수정{% endblock %}

{% block content %}
    <h1> POST 수정</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="수정">
    </form>
{% endblock %}

blog/templates/blog/profile.html
{% extends "layout.html" %}
{% block title %}  
  Profile

{% endblock title %}

{% block content %}

  <h1> {{user.name}}'s Profile </h1>
  <ul>
    <li> 이름:{{user.name}}</li>
    <li>전화번호:{{user.profile.phone_number}}</li>
    <li>주소:{{user.profile.address}}</li>
  </ul>
{% endblock content %}